CREATE DEFINER=`root`@`localhost` PROCEDURE `DeletePerson`(
    IN `p_Id` INT

)
    LANGUAGE SQL
    NOT DETERMINISTIC
    CONTAINS SQL
    SQL SECURITY DEFINER
    COMMENT ''
BEGIN
    DELETE FROM persons WHERE Id=p_Id;
END